ALTER TABLE works ADD COLUMN cos_key TEXT NOT NULL DEFAULT '';
ALTER TABLE works ADD COLUMN cos_url TEXT NOT NULL DEFAULT '';
ALTER TABLE works ADD COLUMN cos_etag TEXT NOT NULL DEFAULT '';
ALTER TABLE works ADD COLUMN upload_status TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE works ADD COLUMN upload_error TEXT NOT NULL DEFAULT '';
ALTER TABLE works ADD COLUMN uploaded_at TEXT NOT NULL DEFAULT '';
